### PR TITLE
CO2

### PR DESCRIPTION
**Pull request by Zachary-Kramer**
This mostly involves the new class swCarbon

@BrendenBe1 is added as more of a optional reviewer

### CODE REVIEW

**Comment by Zachary-Kramer** [comment]
I have a poor understanding of submodules -- at what point should I update it? Before or after the merge?

**Comment by dschlaep** [comment]
Your are referring to merging the CO2-enabled SOILWAT2 branch into the CO2-enabled rSOILWAT2 branch? And then creating a pull-request to merge the CO2-enabled rSOILWAT2 branch into rSOILWAT2 master.

@Zachary-Kramer: I don't see how it is possible to (ci-)test the CO2-enabled rSOILWAT2 branch without having the CO2-enabled SOILWAT2 branch set as submodule (see failing builds). Of course, once the CO2-enabled SOILWAT2 branch is merged into SOILWAT2 master, then you will need to update the tracking submodule to master.

To answer your question directly: update before the merge.

**Comment by Zachary-Kramer** [comment]
I'm investigating why the builds are failing. They're acting as if the submodule was not updated (specifically, it's using the old files.in)

**Comment by Zachary-Kramer** [comment]
@dschlaep the example1 and example2 input data for the automated builds need to be updated since I changed and added .in files. I noticed that these are in the _inst_ folder, which I can easily update. I also noticed Ex1_input.rds and Ex2_input.rds in _tests/testthat._ I haven't touched RDS stuff much -- how do I go about updating those? I used the script in rSFSW2 to update the input.rds before. Thanks.

**Comment by dschlaep** [comment]
> I also noticed Ex1_input.rds and Ex2_input.rds in tests/testthat. I haven't touched RDS stuff much -- how do I go about updating those? I used the script in rSFSW2 to update the sysdata RDS before. 

To read `rds`-files  use the function
```
dat <- readRDS(filename.rds)
```
To save an object in `rds`-format use the function 
```
saveRDS(dat, filename.rds)
```

The specific files `tests/testthat/Ex*_input.rds` are created with the script `data-raw/prepare_testInput_objects.R`. This script grabs the example data from `inst/extdata/example*`.

**Comment by dschlaep** [comment]
Need example with carbon data and CO2-effects turned on to review and test (see issue #54)

**Comment by dschlaep** [comment]
> the example1 and example2 input data for the automated builds need to be updated since I changed and added .in files.

I updated these with commits 40c278a25dc1228f8d257f27deb52352b6e7af6a and 2aee59a24d53f36e02f512a9bd1348b43888fdb9.

Code is not working -- see #57

**Comment by dschlaep** [comment]
The slot `CO2ppm` of class `swCarbon` is a vector. I believe that this should be a matrix with two columns `Year` and the value. Otherwise, it is not as obvious what the code does and what any value means -- difficult to maintain.

**Comment by dschlaep** [comment]
This works on my local machine, but fails on the CIs.

The command `R CMD check` uses on my local machine the `src/makefile` and appropriate `all` target for `checking whether package ‘rSOILWAT2’ can be installed`. However, on travis-ci and appveyor-ci, this check does not use our makefile. Instead, it uses some generic approach and compiles all source files. This includes `SW_Main.c` and `SW_Output_mock.c` which should be excluded otherwise they cause `multiple definition of XXX` errors.

see issue https://github.com/Burke-Lauenroth-Lab/rSOILWAT2/issues/81

**Pull request merged**
